# BuildKit configuration for kali-builder
# Enables automatic cache invalidation when Dockerfile or base images change

debug = false

[worker.oci]
  enabled = true
  # Enable garbage collection
  gc = true

  # Cache storage limits - increased for stable single-run builds
  reservedSpace = "25GB"
  maxUsedSpace = "90GB"
  minFreeSpace = "30GB"

  # Reduce parallelism for stability
  max-parallelism = 4

# GC Policy 1: Minimal interference during builds
# Remove only old temporary contexts with high limits
[[worker.oci.gcpolicy]]
  filters = ["type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
  keepDuration = "72h"
  maxUsedSpace = "85GB"

# GC Policy 2: Main cache preservation with extended retention
[[worker.oci.gcpolicy]]
  keepDuration = "336h"
  reservedSpace = "25GB"
  maxUsedSpace = "90GB"

# GC Policy 3: Unshared cache - careful cleanup
[[worker.oci.gcpolicy]]
  reservedSpace = "20GB"
  maxUsedSpace = "95GB"

# GC Policy 4: Emergency cleanup only at critical disk usage
[[worker.oci.gcpolicy]]
  all = true
  reservedSpace = "15GB"
  maxUsedSpace = "100GB"
